name: Node CI

on: 
  push:
    branches:
    - master
    - 'greenkeeper/*'
  pull_request:
    branches:
    - master
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [13, 12]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and test
      run: |
        npm install
        npm run coverage
      env:
        CI: true
        GREETING: "World"

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}

